- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    server_name: "localhost"
    root_dir: "/var/www/laravel"
    shared_items:
      - .env
      - storage
    timestamp: "{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
    directory:
      root: "{{ root_dir }}"
      current: "{{ root_dir }}/current"
      shared: "{{ root_dir }}/shared"
      release: "{{ root_dir }}/release"
    repo: "git@github.com:FramgiaDockerTeam/laravel-ssh-source.git"

  tasks:
    # Tag source code directory
    - set_fact:
       directory_tag: "{{ directory.release }}/{{ timestamp }}"
    # Detect the very first time run task on host
    - name: Check know_host
      stat: path=/known_host
      register: known_host
    - name: Create known_host
      file: path=/known_host state=touch owner=root group=sys mode=0555
      register: new_host
      when: known_host.stat.exists is defined and known_host.stat.exists == false
    # State of current host
    - debug: var=new_host var=directory_tag
    # Setting up pakages
    - include: task/setup.yml
      when: new_host|changed
    # Create shared file directories
    - include: task/mkdir.yml
    # Config environment
    - include: task/config.yml
    # Make symbolic link
    - include: task/shared.yml
    # Start/restart environment
    - include: task/supervisor.yml
      when: new_host|changed

  handlers:
    - include: task/handlers.yml